##plot 1
data=read.delim("E:\\College stuff\\R programming\\R-Programming_DS-ML\\household_power_consumption.txt",header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
sub<-data[data$Date %in% c('1/2/2007','2/2/2007'),]
globalAcPower<-as.numeric(sub$Global_active_power)
png("plot1.png",width=560,height=480)
hist(globalAcPower,col = 'red',main = 'Global Active Power',xlab = 'Global Active Power (in killowats)')
dev.off()
##plot 2
date2 <- strptime(paste(sub$Date, sub$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalAcPower <- as.numeric(sub$Global_active_power)
png("plot2.png", width=560, height=480)
plot(date2, globalAcPower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.off()
##plot3
date3 <- strptime(paste(sub$Date, sub$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalAcPower <- as.numeric(sub$Global_active_power)
sMetering1 <- as.numeric(sub$Sub_metering_1)
sMetering2 <- as.numeric(sub$Sub_metering_2)
sMetering3 <- as.numeric(sub$Sub_metering_3)
png("plot3.png", width=560, height=480)
plot(date3, sMetering1, type="l", ylab="Energy Submetering", xlab="")
lines(date3, sMetering2, type="l", col="red")
lines(date3, sMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()
##plot4
date3 <- strptime(paste(sub$Date, sub$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(sub$Global_active_power)
globalReactivePower <- as.numeric(sub$Global_reactive_power)
voltage <- as.numeric(sub$Voltage)
subMeter1 <- as.numeric(sub$Sub_metering_1)
subMeter2 <- as.numeric(sub$Sub_metering_2)
subMeter3 <- as.numeric(sub$Sub_metering_3)
png("plot4.png", width=560, height=480)
par(mfrow = c(2, 2)) 
plot(date3, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(date3, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(date3, subMeter1, type="l", ylab="Energy Submetering", xlab="")
lines(date3, subMeter2, type="l", col="red")
lines(date3, subMeter3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(date3, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
